/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_marcinchwedczuk_pipi_arith_JniZF10 */

#ifndef _Included_pl_marcinchwedczuk_pipi_arith_JniZF10
#define _Included_pl_marcinchwedczuk_pipi_arith_JniZF10
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_marcinchwedczuk_pipi_arith_JniZF10
 * Method:    initializeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_marcinchwedczuk_pipi_arith_JniZF10_initializeLibrary
  (JNIEnv *, jclass);

/*
 * Class:     pl_marcinchwedczuk_pipi_arith_JniZF10
 * Method:    cmpAbs
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_pl_marcinchwedczuk_pipi_arith_JniZF10_cmpAbs
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     pl_marcinchwedczuk_pipi_arith_JniZF10
 * Method:    addAbs
 * Signature: ([BI[BILpl/marcinchwedczuk/pipi/arith/JniZF10/DigitsExponentStruct;)V
 */
JNIEXPORT void JNICALL Java_pl_marcinchwedczuk_pipi_arith_JniZF10_addAbs
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jobject);

/*
 * Class:     pl_marcinchwedczuk_pipi_arith_JniZF10
 * Method:    subtractAbs
 * Signature: ([BI[BILpl/marcinchwedczuk/pipi/arith/JniZF10/DigitsExponentStruct;)V
 */
JNIEXPORT void JNICALL Java_pl_marcinchwedczuk_pipi_arith_JniZF10_subtractAbs
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
