/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_marcinchwedczuk_pipi_arith_JniZF10_DigitsExponentStruct */

#ifndef _Included_pl_marcinchwedczuk_pipi_arith_JniZF10_DigitsExponentStruct
#define _Included_pl_marcinchwedczuk_pipi_arith_JniZF10_DigitsExponentStruct
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
